### ISSUE TITLE
(Magic) Weapon generator

### ISSUE THREAD

**Issue by MageCity** [MageCity/LongSphinx#14]
As the title says. Will generate weapons, magical and non.

**Comment by walterw9000** [comment]
Basic weapon generator created, but magical effects still TBD

**Comment by walterw9000** [comment]
Magic effect scratchpad:

'deals {number} extra {type} damage'
'sings you to sleep, so long as it has tasted blood that day.'
'sings you to sleep, so long as it has tasted {species} blood that day.'
'glows in the presence of {species}'

**Comment by MageCity** [comment]
Part specifications? i.e. blade can be a different material than shaft?
