### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by MageCity** [MageCity/LongSphinx#16]
Tim could provide reminder messages. This requires some form of data store, and possibly some way to trigger events at specific times.

**Comment by walterw9000** [comment]
To investigate:
- Do we get enough events (with enough temporal spread) to just react to the first event after the timer goes off?

**Comment by walterw9000** [comment]
We do not have enough temporal spread; we regularly have gaps of multiple hours.

Options:
1. try to figure out coroutines & possibly even schedulers
2. don't care, use reminders at the day level, not hour level
3. don't make a reminder system

**Comment by walterw9000** [comment]
Option 1 was successful; the remaining portion of this task is to make reminders persist across bot restarts.

**Comment by walterw9000** [comment]
Note: there are also some problems involving setting reminders for specific times and having it set for the wrong day.
