### ISSUE TITLE
MediaWiki search

### ISSUE THREAD

**Issue by diziara** [MageCity/LongSphinx#79]
Add support to search a MediaWiki install, ie Memory Alpha, or the emperor LCARS.

Proposed command:
`!LCARS $_searchString`
Or
`!wiki LCARS $_searchString`
The latter would be better for multiple from one command, the former better for simplicity if only one or two are needed?

**Comment by MageCity** [comment]
Resolved by 0c05a584be66e0fdbfc6bb2eb4bc0774a34d6776 though I assume there will be further requests around polishing the output.
