### ISSUE TITLE
Server Notices

### ISSUE THREAD

**Issue by diziara** [MageCity/LongSphinx#96]
A command that would allow a server admin to set one or more messages for users on the server to read.

#### All Users
- `!notice` displays the most recently added notice.
- `!notice list` returns a list of keywords for all existing notices
- `!notice $_keyword` will display the notice associated with that keyword.

#### Admins
- `!notice add $_keyword Message goes here.` If keyword does not exists, makes a new notice. If keyword already exists, will replace existing notice while returning a message that repeats both the replaced and new message in code block and quote block respectively.
- `!notice delete $_keyword` deletes notice.

**Comment by MageCity** [comment]
11154dc23722c57b914f8da9d628ade0afc0e5f0
